algoritmo "Divisivel"

var

   //Declaracao de Variavel
   A : inteiro

inicio

      //Entrada de Dados
      escreva("Digite o Numero: ")
      leia(A)
      
      //Processamento e Saida de Dados
      se ( A MOD 3 = 0 ) entao
      
      escreva(A, " e divisivel por 3")
      
      senao
      
      escreva(A, " nao e divisivel por 3")
      
      fimse
      
fimalgoritmo