Algoritmo "Divisao_Numero_Real

Var
   // Seção de Declarações das variáveis
   A, B: real
   divisao: real
   
Inicio

   //Entrada de Dados

   escreva("Digite um numero: ")
   leia(A)
   
   escreva("Digite um numero: ")
   leia(B)
   
   //Processamento de Dados
   
   divisao <- A / B
   
   //Saida de Dados
   
   escreval("Resultados: ")
   escreval("Divisao: ", divisao)
   
Fimalgoritmo