algoritmo "Maior Numero"

var

   //Declaracao de Variaveis
   
   A, B, Maior : real

inicio

      //Entrada de Dados
      escreva("Digite um numero: ")
      leia (A)
      
      escreva("Digite outro numero: ")
      leia (B)


      //Processamento e Saida de Dados
      se ( A > B ) entao
      escreval("Resultado: ", A)
      
      senao
      escreval("Resultado: ", B)
      
      fimse
      
fimalgoritmo