algoritmo "Par ou Impar Melhorado"

var
   //Declaracao de Variavel
   
   A : inteiro

inicio

      //Entrada de Dados
      escreva("Digite o número desejado: ")
      leia(A)
      
      //Processamento de Dados e Saida de Dados
      se( A MOD 2 = 0 ) entao

      escreva(A, " e par")
      
      senao
      
      escreva(A, " e impar")
      
      fimse
fimalgoritmo