algoritmo "Soma2Numeros"

var

   //Declaraçao de Variaveis
   A, B, C: inteiro

inicio

     //fase entrada de dados

   //comando de saída
   escreva("Digite um numero: ")

   //comando de entrada
   leia(A)

   escreva("Digite outro numero: ")
   leia(B)
   
     //processamento
   C <- A + B

     //fase saida de dados
   escreval()
   escreva("Resultado: ")
   escreva(C)

   
fimalgoritmo