algoritmo "Tabuada Completa"

var

   //Declaracao de Variaveis
   i, j : inteiro

inicio

      //Entrada de Dados

      i <- 1
      j <- 1
      
      enquanto i <= 10 faca
         para j de 1 ate 10 faca

              escreval(i, " x ", j, " = ", i * j)

              
         fimpara
         escreval()
         
      i <- i + 1
      j <- j
      

      fimenquanto
      
fimalgoritmo